name: 'anaconda_upload'
description: 'Anaconda.org Upload'
inputs:
  username:  # id of input
    description: 'anaconda.org username'
    required: true
  password:
    description: 'anaconda.org password'
    required: true
  wheels:
    description: 'folder containing wheels'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: install anaconda client
      shell: bash
      run: |
        pip install anaconda-client anaconda-auth
    - name: login-to-anaconda
      uses: kivy-school/actions/with-post-step@main
      with:
        main: |
          anaconda login \
            --at anaconda.org \
            --username ${{ inputs.username }} \
            --password "${{ inputs.password }}"
        post: anaconda logout --at anaconda.org
    - name: upload-to-anaconda
      shell: bash
      working-directory: ${{ inputs.wheels }}
      run: |
        for FILE in *
          do
            anaconda upload --force $FILE
          done
      

    
