name: 'anaconda_upload'
description: 'Anaconda.org Upload'
inputs:
  username:  # id of input
    description: 'anaconda.org username'
    required: true
  password:
    description: 'anaconda.org password'
    required: true
  wheels:
    description: 'folder containing wheels'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: install anaconda client
      shell: bash
      run: |
        pip install anaconda-client anaconda-auth
        
    - name: login-to-anaconda
      shell: bash
      run: |
        anaconda login \
          --at anaconda.org \
          --username ${{ inputs.username }} \
          --password "${{ inputs.password }}"
          
    - name: upload-to-anaconda
      shell: bash
      continue-on-error: true
      working-directory: ${{ inputs.wheels }}
      run: |
        for FILE in *
          do
            anaconda upload --force $FILE
          done

    - name: logoff
      shell: bash
      run: anaconda logout --at anaconda.org
      

    
