name: 'anaconda_upload'
description: 'Anaconda.org Upload'
inputs:
  username:  # id of input
    description: 'anaconda.org username'
    required: true
  password:
    description: 'anaconda.org password'
    required: true
  wheels:
    description: 'folder containing wheels'
    required: true
  
runs:
  using: "composite"
  post:
      run: anaconda logout --at anaconda.org
  steps:

    - name: install anaconda client
      run: |
        pip install anaconda-client anaconda-auth
      
    - name: login-to-anaconda
      run: |
        anaconda login \
            --at anaconda.org \
            --username ${{ inputs.username }} \
            --password "${{ inputs.password }}"

    - name: upload-to-anaconda
      working-directory: ${{ inputs.wheels }}
      run: |
        for FILE in *
          do
            anaconda upload --force $FILE
          done
      

    
